// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uptime.proto

#ifndef PROTOBUF_uptime_2eproto__INCLUDED
#define PROTOBUF_uptime_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_uptime_2eproto();
void protobuf_AssignDesc_uptime_2eproto();
void protobuf_ShutdownFile_uptime_2eproto();

class Uptime;

// ===================================================================

class Uptime : public ::google::protobuf::Message {
 public:
  Uptime();
  virtual ~Uptime();

  Uptime(const Uptime& from);

  inline Uptime& operator=(const Uptime& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Uptime& default_instance();

  void Swap(Uptime* other);

  // implements Message ----------------------------------------------

  Uptime* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Uptime& from);
  void MergeFrom(const Uptime& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 uptime = 1;
  inline bool has_uptime() const;
  inline void clear_uptime();
  static const int kUptimeFieldNumber = 1;
  inline ::google::protobuf::uint32 uptime() const;
  inline void set_uptime(::google::protobuf::uint32 value);

  // required uint32 idletime = 2;
  inline bool has_idletime() const;
  inline void clear_idletime();
  static const int kIdletimeFieldNumber = 2;
  inline ::google::protobuf::uint32 idletime() const;
  inline void set_idletime(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Uptime)
 private:
  inline void set_has_uptime();
  inline void clear_has_uptime();
  inline void set_has_idletime();
  inline void clear_has_idletime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 uptime_;
  ::google::protobuf::uint32 idletime_;
  friend void  protobuf_AddDesc_uptime_2eproto();
  friend void protobuf_AssignDesc_uptime_2eproto();
  friend void protobuf_ShutdownFile_uptime_2eproto();

  void InitAsDefaultInstance();
  static Uptime* default_instance_;
};
// ===================================================================


// ===================================================================

// Uptime

// required uint32 uptime = 1;
inline bool Uptime::has_uptime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Uptime::set_has_uptime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Uptime::clear_has_uptime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Uptime::clear_uptime() {
  uptime_ = 0u;
  clear_has_uptime();
}
inline ::google::protobuf::uint32 Uptime::uptime() const {
  // @@protoc_insertion_point(field_get:Uptime.uptime)
  return uptime_;
}
inline void Uptime::set_uptime(::google::protobuf::uint32 value) {
  set_has_uptime();
  uptime_ = value;
  // @@protoc_insertion_point(field_set:Uptime.uptime)
}

// required uint32 idletime = 2;
inline bool Uptime::has_idletime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Uptime::set_has_idletime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Uptime::clear_has_idletime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Uptime::clear_idletime() {
  idletime_ = 0u;
  clear_has_idletime();
}
inline ::google::protobuf::uint32 Uptime::idletime() const {
  // @@protoc_insertion_point(field_get:Uptime.idletime)
  return idletime_;
}
inline void Uptime::set_idletime(::google::protobuf::uint32 value) {
  set_has_idletime();
  idletime_ = value;
  // @@protoc_insertion_point(field_set:Uptime.idletime)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_uptime_2eproto__INCLUDED
